/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as TutorialsCreateAndCompleteTaskRouteImport } from './routes/tutorials.create-and-complete-task'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsCreateAndCompleteTaskRoute =
  TutorialsCreateAndCompleteTaskRouteImport.update({
    id: '/tutorials/create-and-complete-task',
    path: '/tutorials/create-and-complete-task',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/tutorials/create-and-complete-task': typeof TutorialsCreateAndCompleteTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/tutorials/create-and-complete-task': typeof TutorialsCreateAndCompleteTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/tutorials/create-and-complete-task': typeof TutorialsCreateAndCompleteTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/boards/$boardId' | '/tutorials/create-and-complete-task'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boards/$boardId' | '/tutorials/create-and-complete-task'
  id:
    | '__root__'
    | '/'
    | '/boards/$boardId'
    | '/tutorials/create-and-complete-task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
  TutorialsCreateAndCompleteTaskRoute: typeof TutorialsCreateAndCompleteTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials/create-and-complete-task': {
      id: '/tutorials/create-and-complete-task'
      path: '/tutorials/create-and-complete-task'
      fullPath: '/tutorials/create-and-complete-task'
      preLoaderRoute: typeof TutorialsCreateAndCompleteTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsBoardIdRoute: BoardsBoardIdRoute,
  TutorialsCreateAndCompleteTaskRoute: TutorialsCreateAndCompleteTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
